version: '3'
services:
  qber:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - SPARQL_ENDPOINT=http://ilz.dimis.fim.uni-passau.de:14182/pypads/query
      - DEFAULT_BASE=https://www.padre-lab.eu/onto
      - LOCAL_SERVER_NAME=http://localhost:5000
      - START_LOCAL_NAME=produced_by
      - DEBUG=True

